using System.Globalization;
using System.Text;

// gen-emoji-presentation: writes src/DIR.Lib/EmojiPresentation.Data.g.cs from the Unicode Character
// Database's emoji-data.txt.
//
//   dotnet run --project tools/gen-emoji-presentation [-- --input <path|url>] [--out <file>]
//
// GENERATED rather than hand-written because the property it encodes is a Unicode fact with one right
// answer, and the wrong answer is invisible: a missing range silently leaves a pictograph drawn from
// the text face, which looks like a font choice rather than a bug. It is also not small enough to
// eyeball (81 ranges over 1219 codepoints at Unicode 17.0) and it MOVES -- every Unicode release adds
// pictographs, and the only honest way to follow that is to re-run this against the new file.
//
// Ranges are merged where they abut, so the emitted table is minimal: the source file lists the
// property per emoji block, which leaves runs like U+1F680..U+1F6C5 split across a dozen entries that
// are one range as far as a lookup is concerned.
//
// Downloading by default is deliberate. The alternative is vendoring a 5,000-line UCD file whose only
// consumer is this tool, to be re-vendored by hand at the exact moment someone is already running the
// tool. Pass --input to point at a local copy when offline or pinning a specific release.

var input = "https://www.unicode.org/Public/UCD/latest/ucd/emoji/emoji-data.txt";
var output = Path.Combine("src", "DIR.Lib", "EmojiPresentation.Data.g.cs");

for (var i = 0; i < args.Length; i++)
{
    var next = i + 1 < args.Length ? args[i + 1] : null;
    switch (args[i])
    {
        case "--input" when next is not null: input = next; i++; break;
        case "--out" when next is not null: output = next; i++; break;
        default:
            Console.Error.WriteLine($"unknown argument '{args[i]}'");
            Console.Error.WriteLine("usage: gen-emoji-presentation [--input <path|url>] [--out <file>]");
            return 2;
    }
}

string text;
if (Uri.TryCreate(input, UriKind.Absolute, out var uri) && uri.Scheme is "http" or "https")
{
    using var http = new HttpClient { Timeout = TimeSpan.FromMinutes(2) };
    text = await http.GetStringAsync(uri);
}
else
{
    text = await File.ReadAllTextAsync(input);
}

// The header carries the version this data IS, which is the one thing a reader of the generated file
// needs and cannot recover from the numbers. Absent (a hand-trimmed input) is not fatal: say so rather
// than guess, since a wrong version claim is worse than none.
var version = HeaderValue(text, "# Version:") ?? "unknown";
var date = HeaderValue(text, "# Date:") ?? "unknown";

var ranges = new List<(uint Start, uint End)>();
foreach (var rawLine in text.Split('\n'))
{
    var line = rawLine;
    var hash = line.IndexOf('#');
    if (hash >= 0) line = line[..hash];

    var semi = line.IndexOf(';');
    if (semi < 0) continue;

    if (!line[(semi + 1)..].Trim().Equals("Emoji_Presentation", StringComparison.Ordinal)) continue;

    var codes = line[..semi].Trim();
    var dots = codes.IndexOf("..", StringComparison.Ordinal);
    var start = uint.Parse(dots < 0 ? codes : codes[..dots], NumberStyles.HexNumber, CultureInfo.InvariantCulture);
    var end = dots < 0 ? start : uint.Parse(codes[(dots + 2)..], NumberStyles.HexNumber, CultureInfo.InvariantCulture);
    ranges.Add((start, end));
}

if (ranges.Count == 0)
{
    Console.Error.WriteLine($"no Emoji_Presentation entries in '{input}'; refusing to write an empty table");
    return 1;
}

ranges.Sort((a, b) => a.Start.CompareTo(b.Start));

// Merge overlapping AND abutting ranges. Abutting matters: a lookup does not care where one emoji
// block ends and the next begins, and merging turns 296 source entries into 81.
var merged = new List<(uint Start, uint End)>();
foreach (var r in ranges)
{
    if (merged.Count > 0 && r.Start <= merged[^1].End + 1)
    {
        merged[^1] = (merged[^1].Start, Math.Max(merged[^1].End, r.End));
    }
    else
    {
        merged.Add(r);
    }
}

var codepoints = merged.Sum(r => (long)(r.End - r.Start + 1));

var sb = new StringBuilder();
sb.Append("// <auto-generated>\n");
sb.Append("//     Generated by tools/gen-emoji-presentation. Do not edit by hand.\n");
sb.Append("//\n");
sb.Append($"//     Source:   {input}\n");
sb.Append($"//     Version:  Unicode emoji-data {version} ({date})\n");
sb.Append($"//     Contents: {merged.Count} merged ranges over {codepoints} codepoints.\n");
sb.Append("//\n");
sb.Append("//     Regenerate: dotnet run --project tools/gen-emoji-presentation\n");
sb.Append("// </auto-generated>\n");
sb.Append("\n");
sb.Append("namespace DIR.Lib;\n");
sb.Append("\n");
sb.Append("public static partial class EmojiPresentation\n");
sb.Append("{\n");
sb.Append("    /// <summary>The Unicode emoji-data release this table was generated from.</summary>\n");
sb.Append($"    public const string UnicodeVersion = \"{version}\";\n");
sb.Append("\n");
sb.Append("    /// <summary>\n");
sb.Append("    /// Every codepoint with <c>Emoji_Presentation=Yes</c>, as inclusive [start, end] pairs\n");
sb.Append("    /// laid out flat, ascending, non-overlapping and merged where they abut -- the shape\n");
sb.Append("    /// <see cref=\"IsDefaultFor(int)\"/>'s binary search expects.\n");
sb.Append("    /// </summary>\n");
sb.Append("    // internal, not private, so the tests can check the table is sorted and disjoint,\n");
sb.Append("    // and that the binary search over it agrees with a linear scan -- the two ways a\n");
sb.Append("    // regenerated table could be wrong without any single lookup looking wrong.\n");
sb.Append("    internal static readonly uint[] DefaultPresentationRanges =\n");
sb.Append("    [\n");
foreach (var (start, end) in merged)
{
    sb.Append($"        0x{start:X4}, 0x{end:X4},\n");
}
sb.Append("    ];\n");
sb.Append("}\n");

// CRLF explicitly, not Environment.NewLine: the repo's C# is CRLF and the file is committed, so a run
// on Linux would otherwise rewrite all 100-odd lines as a line-ending-only diff.
var content = sb.Replace("\n", "\r\n").ToString();

var dir = Path.GetDirectoryName(Path.GetFullPath(output));
if (!string.IsNullOrEmpty(dir)) Directory.CreateDirectory(dir);
await File.WriteAllTextAsync(output, content, new UTF8Encoding(false));

Console.WriteLine($"[gen-emoji-presentation] {output}: {merged.Count} ranges, {codepoints} codepoints, emoji-data {version}");
return 0;

static string? HeaderValue(string text, string prefix)
{
    foreach (var rawLine in text.Split('\n'))
    {
        var line = rawLine.Trim();
        if (line.StartsWith(prefix, StringComparison.Ordinal))
        {
            // "# Date: 2025-07-25, 17:54:31 GMT" -- the day is the useful half; the time of day says
            // nothing a reader of the generated table can act on.
            var value = line[prefix.Length..].Trim();
            var comma = value.IndexOf(',');
            return comma < 0 ? value : value[..comma];
        }
    }
    return null;
}
