using System.Reflection;

namespace DIR.Lib.Color;

/// <summary>
/// Bundled ICC profiles distributed with DIR.Lib. Callers that want their
/// TIFF / PNG output to round-trip through colour-managed viewers (PixInsight,
/// Lightroom, browsers) without supplying their own profile bytes can pass
/// one of these directly to <c>TiffPageOptions.IccProfile</c> or to the
/// <c>PngWriter.Encode(..., iccProfile)</c> overload.
///
/// The bundled sRGB profile is a 588-byte v4 profile generated by LittleCMS
/// (the same engine that ships in Pillow / GIMP / Krita). v4 is the modern
/// recommended encoding from the ICC and is round-tripped correctly by every
/// major image library; the binary blob lives at <c>Color/sRGB-v4.icc</c>
/// and is loaded lazily on first access.
/// </summary>
public static class IccProfiles
{
    private static readonly Lazy<byte[]> _sRgbV4 = new(() => LoadEmbeddedResource("DIR.Lib.Color.sRGB-v4.icc"));

    /// <summary>
    /// sRGB IEC61966-2.1 v4 ICC profile (588 bytes). Public domain — generated
    /// by LittleCMS. Use this when writing colour-managed output that should be
    /// interpreted as sRGB by downstream readers.
    /// </summary>
    public static ReadOnlyMemory<byte> SRgbV4 => _sRgbV4.Value;

    private static byte[] LoadEmbeddedResource(string logicalName)
    {
        var asm = typeof(IccProfiles).Assembly;
        using var stream = asm.GetManifestResourceStream(logicalName)
            ?? throw new InvalidOperationException($"Embedded resource '{logicalName}' not found in {asm.GetName().Name}.");
        using var ms = new MemoryStream(capacity: (int)stream.Length);
        stream.CopyTo(ms);
        return ms.ToArray();
    }
}
